<?php

return [
    'merge' => [
        'h1'               => 'Unire PDF',
        'h2'               => 'Unisci PDF, Word, Excel, PowerPoint, JPG e PNG in un unico documento',
        'description'      => 'Unisci PDF, Word, Excel, PowerPoint e immagini in un unico PDF',
        'meta_description' => 'Unire PDF — unisci PDF, Word, Excel, PowerPoint e immagini in un unico documento, subito e online. Veloce, sicuro e senza installare nulla.',
        'action_label'     => 'Unisci i file',
    ],
    'compress' => [
        'h1'               => 'Comprimere PDF',
        'h2'               => 'Riduci le dimensioni del tuo PDF online, senza perdere qualità',
        'description'      => 'Riduci le dimensioni dei file PDF online senza perdere qualità',
        'meta_description' => 'Comprimere PDF — riduci le dimensioni dei tuoi file PDF online. Veloce, gratis da provare e senza perdita di qualità.',
        'action_label'     => 'Comprimi',
    ],
    'image-to-pdf' => [
        'h1'               => 'Convertire immagine in PDF',
        'h2'               => 'Converti qualsiasi immagine in PDF: JPG, PNG, GIF, BMP, WebP e altri',
        'description'      => 'Converti qualsiasi formato immagine in PDF — JPG, PNG, GIF, BMP, WebP, TIFF, SVG',
        'meta_description' => 'Convertire immagine in PDF — trasforma JPG, PNG, GIF, BMP, WebP, TIFF o SVG in un documento PDF subito. Online, senza installare nulla.',
        'action_label'     => 'Converti in PDF',
    ],
    'jpg-to-pdf' => [
        'h1'               => 'Converti JPG in PDF',
        'h2'               => 'Trasforma jpg in pdf subito: una o più immagini in un unico documento',
        'description'      => 'Trasforma immagini in documenti PDF subito',
        'meta_description' => 'Converti JPG in PDF — trasforma jpg in pdf online, anche più immagini in un unico documento. Veloce, sicuro e senza registrazione.',
        'action_label'     => 'Crea PDF',
    ],
    'pdf-to-word' => [
        'h1'               => 'Converti PDF in Word',
        'h2'               => 'Trasforma pdf in word: documento modificabile, formattazione intatta',
        'description'      => 'Convertire PDF in Word: documenti modificabili in pochi secondi',
        'meta_description' => 'Converti PDF in Word — trasforma pdf in word online e ottieni un documento .docx modificabile. Formattazione conservata, nessuna installazione.',
        'action_label'     => 'Converti in Word',
    ],
    'word-to-pdf' => [
        'h1'               => 'Convertire Word in PDF',
        'h2'               => 'Salva i tuoi documenti Word in PDF, con il layout intatto',
        'description'      => 'Converti documenti Word in PDF subito',
        'meta_description' => 'Convertire Word in PDF — converti i tuoi documenti .doc e .docx in file PDF subito. Layout e font conservati, tutto online.',
        'action_label'     => 'Converti in PDF',
    ],
    'pdf-to-jpg' => [
        'h1'               => 'Convertire PDF in JPG',
        'h2'               => 'Estrai ogni pagina del PDF come immagine JPG di alta qualità',
        'description'      => 'Converti le pagine PDF in immagini JPG',
        'meta_description' => 'Convertire PDF in JPG — estrai le pagine del tuo PDF come immagini JPG di alta qualità. Veloce e online.',
        'action_label'     => 'Converti in JPG',
    ],
    'split' => [
        'h1'               => 'Dividere PDF',
        'h2'               => 'Separa un PDF in più file o estrai solo le pagine che ti servono',
        'description'      => 'Dividi un PDF in più file',
        'meta_description' => 'Dividere PDF — separa il tuo PDF in più file o estrai solo le pagine che ti servono. Online, senza installare nulla.',
        'action_label'     => 'Dividi',
    ],
    'edit' => [
        'h1'               => 'Modificare PDF',
        'h2'               => 'Aggiungi testo, immagini e annotazioni al tuo PDF dal browser',
        'description'      => 'Modifica il tuo PDF online: testo, immagini e annotazioni',
        'meta_description' => 'Modificare PDF — aggiungi testo, immagini e annotazioni al tuo PDF direttamente dal browser. Nessun programma da installare.',
        'action_label'     => 'Modifica',
    ],
    'sign' => [
        'h1'               => 'Firmare PDF',
        'h2'               => 'Firma i tuoi PDF online: disegna, carica o scrivi la tua firma',
        'description'      => 'Firma documenti PDF online',
        'meta_description' => 'Firmare PDF — firma i tuoi documenti PDF online: disegna la firma, caricala come immagine o scrivila. Veloce e sicuro.',
        'action_label'     => 'Firma',
    ],
    'pdf-to-excel' => [
        'h1'               => 'Convertire PDF in Excel',
        'h2'               => 'Estrai le tabelle dal PDF in un foglio di calcolo modificabile',
        'description'      => 'Converti PDF in fogli di calcolo Excel',
        'meta_description' => 'Convertire PDF in Excel — estrai le tabelle dal tuo PDF in un foglio di calcolo .xlsx modificabile. Online e senza registrazione.',
        'action_label'     => 'Converti in Excel',
    ],
    'excel-to-pdf' => [
        'h1'               => 'Convertire Excel in PDF',
        'h2'               => 'Trasforma i tuoi fogli di calcolo in PDF, con il layout intatto',
        'description'      => 'Converti fogli di calcolo Excel in PDF',
        'meta_description' => 'Convertire Excel in PDF — trasforma i tuoi file .xls e .xlsx in PDF pronti da condividere o stampare. Veloce e online.',
        'action_label'     => 'Converti in PDF',
    ],
    'rotate' => [
        'h1'               => 'Ruotare PDF',
        'h2'               => 'Gira le pagine del tuo PDF e salva l\'orientamento corretto',
        'description'      => 'Ruota le pagine del tuo PDF e salvale',
        'meta_description' => 'Ruotare PDF — gira le pagine del tuo PDF di 90, 180 o 270 gradi e salva l\'orientamento corretto. Online e gratuito da provare.',
        'action_label'     => 'Ruota',
    ],
    'protect' => [
        'h1'               => 'Proteggere PDF con password',
        'h2'               => 'Aggiungi una password al tuo PDF e blocca gli accessi indesiderati',
        'description'      => 'Proteggi il tuo PDF con una password',
        'meta_description' => 'Proteggere PDF — aggiungi una password al tuo documento PDF e blocca gli accessi indesiderati. Crittografia sicura, tutto online.',
        'action_label'     => 'Proteggi',
    ],
    'unlock' => [
        'h1'               => 'Sbloccare PDF',
        'h2'               => 'Rimuovi la password dal tuo PDF e torna a usarlo liberamente',
        'description'      => 'Rimuovi la password dal tuo PDF',
        'meta_description' => 'Sbloccare PDF — rimuovi la password dai tuoi documenti PDF e torna a stamparli e copiarli liberamente. Veloce e online.',
        'action_label'     => 'Sblocca',
    ],
    'watermark' => [
        'h1'               => 'Aggiungere filigrana al PDF',
        'h2'               => 'Inserisci un testo o un logo in filigrana su ogni pagina del PDF',
        'description'      => 'Aggiungi una filigrana di testo o immagine al tuo PDF',
        'meta_description' => 'Aggiungere filigrana al PDF — inserisci un testo o un logo in filigrana su ogni pagina del documento. Posizione e trasparenza regolabili.',
        'action_label'     => 'Aggiungi filigrana',
    ],
    'page-numbers' => [
        'h1'               => 'Aggiungere numeri di pagina al PDF',
        'h2'               => 'Numera le pagine del tuo PDF scegliendo posizione e stile',
        'description'      => 'Aggiungi i numeri di pagina al tuo PDF',
        'meta_description' => 'Aggiungere numeri di pagina al PDF — numera le pagine del tuo documento scegliendo posizione, formato e pagina di partenza. Online.',
        'action_label'     => 'Aggiungi numeri',
    ],
    'pdf-to-ppt' => [
        'h1'               => 'Convertire PDF in PowerPoint',
        'h2'               => 'Trasforma il tuo PDF in una presentazione modificabile',
        'description'      => 'Converti PDF in presentazioni PowerPoint',
        'meta_description' => 'Convertire PDF in PowerPoint — trasforma il tuo PDF in una presentazione .pptx modificabile, diapositiva per diapositiva. Online.',
        'action_label'     => 'Converti in PowerPoint',
    ],
    'ppt-to-pdf' => [
        'h1'               => 'Convertire PowerPoint in PDF',
        'h2'               => 'Salva le tue presentazioni in PDF, pronte da condividere',
        'description'      => 'Converti presentazioni PowerPoint in PDF',
        'meta_description' => 'Convertire PowerPoint in PDF — salva le tue presentazioni .ppt e .pptx in PDF pronti da inviare o stampare. Veloce e online.',
        'action_label'     => 'Converti in PDF',
    ],
    'pdf-to-png' => [
        'h1'               => 'Convertire PDF in PNG',
        'h2'               => 'Esporta le pagine del PDF come immagini PNG nitide',
        'description'      => 'Converti le pagine PDF in immagini PNG',
        'meta_description' => 'Convertire PDF in PNG — esporta le pagine del tuo PDF come immagini PNG nitide, con sfondo trasparente dove serve. Online.',
        'action_label'     => 'Converti in PNG',
    ],
    'png-to-pdf' => [
        'h1'               => 'Convertire PNG in PDF',
        'h2'               => 'Unisci le tue immagini PNG in un unico documento PDF',
        'description'      => 'Converti immagini PNG in un documento PDF',
        'meta_description' => 'Convertire PNG in PDF — unisci una o più immagini PNG in un unico documento PDF. Veloce, sicuro e senza registrazione.',
        'action_label'     => 'Crea PDF',
    ],
    'ocr' => [
        'h1'               => 'OCR: riconoscimento del testo nei PDF',
        'h2'               => 'Rendi ricercabile un PDF scansionato con il riconoscimento del testo',
        'description'      => 'Riconosci il testo nei PDF scansionati (OCR)',
        'meta_description' => 'OCR PDF — rendi ricercabile e copiabile un PDF scansionato con il riconoscimento ottico dei caratteri. Online, senza installare nulla.',
        'action_label'     => 'Riconosci il testo',
    ],
    'remove-pages' => [
        'h1'               => 'Rimuovere pagine da un PDF',
        'h2'               => 'Elimina le pagine che non ti servono e scarica il PDF pulito',
        'description'      => 'Elimina pagine dal tuo PDF',
        'meta_description' => 'Rimuovere pagine da un PDF — elimina le pagine che non ti servono e scarica il documento pulito in pochi secondi. Online.',
        'action_label'     => 'Rimuovi le pagine',
    ],
    'extract-pages' => [
        'h1'               => 'Estrarre pagine da un PDF',
        'h2'               => 'Scegli le pagine che ti interessano e salvale come nuovo PDF',
        'description'      => 'Estrai pagine dal tuo PDF',
        'meta_description' => 'Estrarre pagine da un PDF — scegli le pagine che ti interessano e salvale come nuovo documento PDF. Veloce e online.',
        'action_label'     => 'Estrai le pagine',
    ],
    'html-to-pdf' => [
        'h1'               => 'Convertire HTML in PDF',
        'h2'               => 'Trasforma una pagina web o un file HTML in un PDF da archiviare',
        'description'      => 'Converti pagine web e file HTML in PDF',
        'meta_description' => 'Convertire HTML in PDF — trasforma una pagina web o un file HTML in un documento PDF pronto da archiviare o stampare. Online.',
        'action_label'     => 'Converti in PDF',
    ],
    'optimize' => [
        'h1'               => 'Ottimizzare PDF',
        'h2'               => 'Alleggerisci e velocizza il tuo PDF senza rovinarne la qualità',
        'description'      => 'Ottimizza il tuo PDF per il web',
        'meta_description' => 'Ottimizzare PDF — alleggerisci e velocizza il tuo documento PDF per il web e per l\'invio via email, senza rovinarne la qualità.',
        'action_label'     => 'Ottimizza',
    ],
];
