<?php

return [
    'merge' => [
        'h1'               => 'Îmbinare PDF',
        'h2'               => 'Combină PDF, Word, Excel, PowerPoint, JPG și PNG într-un singur document',
        'description'      => 'Combină PDF, Word, Excel, PowerPoint și imagini într-un singur PDF',
        'meta_description' => 'Îmbinare PDF — combină PDF, Word, Excel, PowerPoint și imagini într-un document instant online. Rapid, sigur și fără instalare.',
        'action_label'     => 'Îmbinare fișiere',
    ],
    'compress' => [
        'h1'               => 'Comprimă PDF',
        'h2'               => 'Reduce dimensiunea fișierului PDF online — fără pierdere de calitate',
        'description'      => 'Reduce dimensiunea fișierului PDF online fără pierdere de calitate',
        'meta_description' => 'Comprimă PDF — reduce dimensiunea fișierelor PDF online. Rapid și fără pierdere de calitate.',
        'action_label'     => 'Comprimă',
    ],
    'image-to-pdf' => [
        'h1'               => 'Imagine la PDF',
        'h2'               => 'Convertește orice imagine la PDF instant — JPG, PNG, GIF, BMP, WebP și altele',
        'description'      => 'Convertește orice format de imagine la PDF — JPG, PNG, GIF, BMP, WebP, TIFF, SVG',
        'meta_description' => 'Imagine la PDF — convertește orice imagine (JPG, PNG, GIF, BMP, WebP, TIFF, SVG) la un document PDF instant. Rapid, sigur și online.',
        'action_label'     => 'Convertește la PDF',
    ],
    'jpg-to-pdf' => [
        'h1'               => 'JPG la PDF',
        'h2'               => 'Convertește imagini la PDF instant — JPG, PNG și altele',
        'description'      => 'Convertește imagini la documente PDF instant',
        'meta_description' => 'JPG la PDF — convertește imagini la documente PDF instant. Suportă JPG, PNG și alte formate.',
        'action_label'     => 'Creează PDF',
    ],
    'pdf-to-word' => [
        'h1'               => 'PDF la Word',
        'h2'               => 'Convertește PDF la document Word — editabil și formatat',
        'description'      => 'Convertește PDF la documente Word editabile',
        'meta_description' => 'PDF la Word — convertește fișiere PDF la documente Word editabile. Formatare păstrată.',
        'action_label'     => 'Convertește la Word',
    ],
    'word-to-pdf' => [
        'h1'               => 'Word la PDF',
        'h2'               => 'Salvează documente Word ca PDF instant',
        'description'      => 'Convertește documente Word la PDF instant',
        'meta_description' => 'Word la PDF — convertește documente Word la fișiere PDF instant. Rapid și ușor online.',
        'action_label'     => 'Convertește la PDF',
    ],
    'pdf-to-jpg' => [
        'h1'               => 'PDF la JPG',
        'h2'               => 'Exportă paginile PDF ca imagini — calitate înaltă',
        'description'      => 'Exportă paginile PDF ca imagini JPG de calitate înaltă',
        'meta_description' => 'PDF la JPG — exportă paginile PDF ca imagini JPG de calitate înaltă. Rapid și online.',
        'action_label'     => 'Convertește la JPG',
    ],
    'split' => [
        'h1'               => 'Desparte PDF',
        'h2'               => 'Desparte PDF — extrage și separă pagini',
        'description'      => 'Desparte fișiere PDF și extrage pagini individuale',
        'meta_description' => 'Desparte PDF — desparte fișiere PDF și extrage pagini individuale. Rapid și online.',
        'action_label'     => 'Desparte PDF',
    ],
    'edit' => [
        'h1'               => 'Editează PDF',
        'h2'               => 'Editează PDF online — adaugă text, imagini și adnotări',
        'description'      => 'Editează fișiere PDF online cu instrumente simple',
        'meta_description' => 'Editează PDF — editează fișiere PDF online. Adaugă text, imagini, adnotări.',
        'action_label'     => 'Editează PDF',
    ],
    'sign' => [
        'h1'               => 'Semnează PDF',
        'h2'               => 'Adaugă semnătura digitală la PDF instant',
        'description'      => 'Semnează documente PDF cu semnătura ta digitală',
        'meta_description' => 'Semnează PDF — adaugă semnătura digitală la documente PDF instant. Rapid și sigur.',
        'action_label'     => 'Semnează PDF',
    ],
    'pdf-to-excel' => [
        'h1'               => 'PDF la Excel',
        'h2'               => 'Convertește PDF la foi de calcul Excel',
        'description'      => 'Convertește PDF la fișiere Excel editabile',
        'meta_description' => 'PDF la Excel — convertește fișiere PDF la foi de calcul Excel editabile. Rapid și online.',
        'action_label'     => 'Convertește la Excel',
    ],
    'excel-to-pdf' => [
        'h1'               => 'Excel la PDF',
        'h2'               => 'Salvează foi de calcul Excel ca PDF',
        'description'      => 'Convertește fișiere Excel la documente PDF',
        'meta_description' => 'Excel la PDF — convertește fișiere Excel la documente PDF instant.',
        'action_label'     => 'Convertește la PDF',
    ],
    'rotate' => [
        'h1'               => 'Rotește PDF',
        'h2'               => 'Rotește paginile PDF online — 90°, 180° sau 270°',
        'description'      => 'Rotește paginile din fișierele PDF online',
        'meta_description' => 'Rotește PDF — rotește paginile PDF online. Alege 90°, 180° sau 270°.',
        'action_label'     => 'Rotește',
    ],
    'protect' => [
        'h1'               => 'Protejează PDF',
        'h2'               => 'Adaugă parolă la fișierul tău PDF',
        'description'      => 'Protejează fișierele PDF cu o parolă',
        'meta_description' => 'Protejează PDF cu parolă — adaugă protecție prin parolă la fișierele PDF online.',
        'action_label'     => 'Adaugă parolă',
    ],
    'unlock' => [
        'h1'               => 'Deblochează PDF',
        'h2'               => 'Elimină protecția prin parolă din PDF',
        'description'      => 'Elimină parola și restricțiile din fișierele PDF',
        'meta_description' => 'Deblochează PDF — elimină protecția prin parolă din fișierele PDF online.',
        'action_label'     => 'Deblochează',
    ],
    'watermark' => [
        'h1'               => 'Adaugă filigran',
        'h2'               => 'Adaugă un filigran text sau imagine la PDF',
        'description'      => 'Adaugă filigran la fișierele tale PDF',
        'meta_description' => 'Filigran PDF — adaugă filigran text sau imagine la documente PDF online.',
        'action_label'     => 'Adaugă filigran',
    ],
    'page-numbers' => [
        'h1'               => 'Adaugă numere de pagini',
        'h2'               => 'Numerotează paginile PDF online',
        'description'      => 'Adaugă numere de pagini la fișierele PDF',
        'meta_description' => 'Numere de pagini PDF — adaugă numere de pagini la documentele PDF online.',
        'action_label'     => 'Adaugă numere',
    ],
    'pdf-to-ppt' => [
        'h1'               => 'PDF la PowerPoint',
        'h2'               => 'Convertește PDF la prezentare PowerPoint editabilă',
        'description'      => 'Convertește PDF la fișiere PowerPoint editabile',
        'meta_description' => 'PDF la PowerPoint — convertește fișiere PDF la prezentări PowerPoint editabile. Rapid și online.',
        'action_label'     => 'Convertește la PowerPoint',
    ],
    'ppt-to-pdf' => [
        'h1'               => 'PowerPoint la PDF',
        'h2'               => 'Convertește prezentări PowerPoint la PDF',
        'description'      => 'Salvează prezentările PowerPoint ca documente PDF',
        'meta_description' => 'PowerPoint la PDF — convertește prezentări PowerPoint la documente PDF instant.',
        'action_label'     => 'Convertește la PDF',
    ],
    'pdf-to-png' => [
        'h1'               => 'PDF la PNG',
        'h2'               => 'Exportă paginile PDF ca imagini PNG',
        'description'      => 'Exportă paginile PDF ca imagini PNG de calitate înaltă',
        'meta_description' => 'PDF la PNG — exportă paginile PDF ca imagini PNG de calitate înaltă. Rapid și online.',
        'action_label'     => 'Convertește la PNG',
    ],
    'png-to-pdf' => [
        'h1'               => 'PNG la PDF',
        'h2'               => 'Convertește imagini PNG la PDF',
        'description'      => 'Convertește imagini PNG la documente PDF',
        'meta_description' => 'PNG la PDF — convertește imagini PNG la documente PDF instant.',
        'action_label'     => 'Creează PDF',
    ],
    'ocr' => [
        'h1'               => 'Recunoaștere text (OCR)',
        'h2'               => 'Extrage text din PDF scanate sau imagini',
        'description'      => 'Recunoaștere optică a caracterelor din PDF și imagini',
        'meta_description' => 'OCR PDF — extrage și recunoaște text din PDF scanate și imagini. Rapid și precis online.',
        'action_label'     => 'Recunoaște text',
    ],
    'remove-pages' => [
        'h1'               => 'Eliminare pagini',
        'h2'               => 'Șterge pagini din documentul PDF',
        'description'      => 'Elimină paginile nedorite din fișierele PDF',
        'meta_description' => 'Eliminare pagini PDF — șterge pagini individuale din documente PDF online.',
        'action_label'     => 'Elimină pagini',
    ],
    'extract-pages' => [
        'h1'               => 'Extragere pagini',
        'h2'               => 'Extrage pagini specifice din PDF',
        'description'      => 'Extrage paginile selectate din fișierele PDF',
        'meta_description' => 'Extragere pagini PDF — extrage pagini specifice din documentele PDF online.',
        'action_label'     => 'Extrage pagini',
    ],
    'html-to-pdf' => [
        'h1'               => 'HTML la PDF',
        'h2'               => 'Convertește pagini web sau HTML la PDF',
        'description'      => 'Convertește fișiere HTML sau URL-uri web la documente PDF',
        'meta_description' => 'HTML la PDF — convertește pagini web și fișiere HTML la documente PDF instant.',
        'action_label'     => 'Convertește la PDF',
    ],
    'optimize' => [
        'h1'               => 'Optimizare PDF',
        'h2'               => 'Optimizează fișierele PDF pentru web sau arhivare',
        'description'      => 'Optimizează fișierele PDF pentru dimensiune și compatibilitate',
        'meta_description' => 'Optimizare PDF — optimizează documentele PDF pentru web, email sau arhivare. Rapid și online.',
        'action_label'     => 'Optimizează',
    ],
];
