<?php

return [
    'merge' => [
        'h1' => 'Merge PDF',
        'h2' => 'Combine multiple PDF files online — fast and easy',
        'description' => 'Combine multiple PDF files into one document online',
        'meta_description' => 'Merge PDF — combine multiple PDF files into one document instantly online. Fast, secure, and no installation required.',
        'action_label' => 'Merge Files',
    ],
    'compress' => [
        'h1' => 'Compress PDF',
        'h2' => 'Reduce PDF file size online — without quality loss',
        'description' => 'Reduce PDF file size online without losing quality',
        'meta_description' => 'Compress PDF — reduce the file size of your PDF documents online. Fast and without quality loss.',
        'action_label' => 'Compress',
    ],
    'jpg-to-pdf' => [
        'h1' => 'JPG to PDF',
        'h2' => 'Convert images to PDF instantly — JPG, PNG and more',
        'description' => 'Convert images to PDF documents instantly',
        'meta_description' => 'JPG to PDF — convert images to PDF documents instantly. Supports JPG, PNG and more formats.',
        'action_label' => 'Create PDF',
    ],
    'pdf-to-word' => [
        'h1' => 'PDF to Word',
        'h2' => 'Convert PDF to Word document — editable & formatted',
        'description' => 'Convert PDF to editable Word documents',
        'meta_description' => 'PDF to Word — convert PDF files to editable Word documents. Formatting preserved.',
        'action_label' => 'Convert to Word',
    ],
    'word-to-pdf' => [
        'h1' => 'Word to PDF',
        'h2' => 'Save Word documents as PDF instantly',
        'description' => 'Convert Word documents to PDF instantly',
        'meta_description' => 'Word to PDF — convert Word documents to PDF files instantly. Fast and easy online.',
        'action_label' => 'Convert to PDF',
    ],
    'pdf-to-jpg' => [
        'h1' => 'PDF to JPG',
        'h2' => 'Export PDF pages as images — high quality',
        'description' => 'Export PDF pages as high quality JPG images',
        'meta_description' => 'PDF to JPG — export PDF pages as high quality JPG images. Fast and online.',
        'action_label' => 'Convert to JPG',
    ],
    'split' => [
        'h1' => 'Split PDF',
        'h2' => 'Split PDF — extract & separate pages',
        'description' => 'Split PDF files and extract individual pages',
        'meta_description' => 'Split PDF — split PDF files and extract individual pages. Fast and online.',
        'action_label' => 'Split PDF',
    ],
    'edit' => [
        'h1' => 'Edit PDF',
        'h2' => 'Edit PDF files online — modify text & pages',
        'description' => 'Edit PDF files directly online',
        'meta_description' => 'Edit PDF — edit PDF files directly online. Modify text, rearrange pages and more.',
        'action_label' => 'Edit PDF',
    ],
    'sign' => [
        'h1' => 'Sign PDF',
        'h2' => 'Add digital signature to PDF — secure & easy',
        'description' => 'Add your digital signature to PDF documents',
        'meta_description' => 'Sign PDF — add your digital signature securely to PDF documents. Online and without software.',
        'action_label' => 'Sign',
    ],
    'pdf-to-excel' => [
        'h1' => 'PDF to Excel',
        'h2' => 'Convert PDF tables to editable Excel files',
        'description' => 'Convert PDF tables to Excel spreadsheets',
        'meta_description' => 'PDF to Excel — convert PDF tables to editable Excel files. Fast and online.',
        'action_label' => 'Convert to Excel',
    ],
    'excel-to-pdf' => [
        'h1' => 'Excel to PDF',
        'h2' => 'Save Excel files as PDF instantly',
        'description' => 'Convert Excel files to PDF documents',
        'meta_description' => 'Excel to PDF — convert Excel files to PDF documents instantly. Fast and online.',
        'action_label' => 'Convert to PDF',
    ],
    'rotate' => [
        'h1' => 'Rotate PDF',
        'h2' => 'Rotate PDF pages — 90°, 180° or 270°',
        'description' => 'Rotate PDF pages by 90°, 180° or 270°',
        'meta_description' => 'Rotate PDF — rotate PDF pages by 90°, 180° or 270°. Fast and online.',
        'action_label' => 'Rotate',
    ],
    'protect' => [
        'h1' => 'Protect PDF',
        'h2' => 'Password protect your PDF — secure encryption',
        'description' => 'Protect PDF files with a password',
        'meta_description' => 'Protect PDF — secure your PDF files with password protection. Fast and online.',
        'action_label' => 'Protect',
    ],
    'unlock' => [
        'h1' => 'Unlock PDF',
        'h2' => 'Remove password protection from PDF',
        'description' => 'Remove password protection from PDF files',
        'meta_description' => 'Unlock PDF — remove password protection from PDF files. Fast and online.',
        'action_label' => 'Unlock',
    ],
    'watermark' => [
        'h1' => 'Add Watermark',
        'h2' => 'Add text watermark to PDF files',
        'description' => 'Add a text watermark to PDF documents',
        'meta_description' => 'Add Watermark — add a text watermark to your PDF files. Fast and online.',
        'action_label' => 'Add Watermark',
    ],
    'page-numbers' => [
        'h1' => 'Add Page Numbers',
        'h2' => 'Add page numbers to PDF documents',
        'description' => 'Add page numbers to PDF files',
        'meta_description' => 'Add Page Numbers — add page numbers to your PDF documents. Fast and online.',
        'action_label' => 'Add Page Numbers',
    ],
    'pdf-to-ppt' => [
        'h1' => 'PDF to PowerPoint',
        'h2' => 'Convert PDF to PowerPoint presentation — editable',
        'description' => 'Convert PDF files to editable PowerPoint presentations',
        'meta_description' => 'PDF to PowerPoint — convert PDF files to editable PowerPoint presentations. Fast and online.',
        'action_label' => 'Convert to PowerPoint',
    ],
    'ppt-to-pdf' => [
        'h1' => 'PowerPoint to PDF',
        'h2' => 'Save PowerPoint presentations as PDF instantly',
        'description' => 'Convert PowerPoint presentations to PDF',
        'meta_description' => 'PowerPoint to PDF — convert PowerPoint presentations to PDF files instantly. Fast and online.',
        'action_label' => 'Convert to PDF',
    ],
    'pdf-to-png' => [
        'h1' => 'PDF to PNG',
        'h2' => 'Export PDF pages as PNG images — high quality',
        'description' => 'Export PDF pages as high quality PNG images',
        'meta_description' => 'PDF to PNG — export PDF pages as high quality PNG images. Fast and online.',
        'action_label' => 'Convert to PNG',
    ],
    'png-to-pdf' => [
        'h1' => 'PNG to PDF',
        'h2' => 'Convert PNG images to PDF instantly',
        'description' => 'Convert PNG images to PDF documents',
        'meta_description' => 'PNG to PDF — convert PNG images to PDF documents instantly. Fast and online.',
        'action_label' => 'Create PDF',
    ],
    'ocr' => [
        'h1' => 'OCR — Recognize Text',
        'h2' => 'Recognize text from scanned PDFs — OCR',
        'description' => 'Recognize text from scanned PDF documents',
        'meta_description' => 'OCR — recognize text from scanned PDF documents. Fast and online.',
        'action_label' => 'Recognize Text',
    ],
    'remove-pages' => [
        'h1' => 'Remove Pages',
        'h2' => 'Remove individual pages from PDF documents',
        'description' => 'Remove specific pages from PDF files',
        'meta_description' => 'Remove Pages — remove individual pages from PDF documents. Fast and online.',
        'action_label' => 'Remove Pages',
    ],
    'extract-pages' => [
        'h1' => 'Extract Pages',
        'h2' => 'Extract specific pages from PDF documents',
        'description' => 'Extract specific pages from PDF files',
        'meta_description' => 'Extract Pages — extract specific pages from PDF documents. Fast and online.',
        'action_label' => 'Extract Pages',
    ],
    'html-to-pdf' => [
        'h1' => 'HTML to PDF',
        'h2' => 'Convert HTML code to PDF documents instantly',
        'description' => 'Convert HTML code to PDF documents',
        'meta_description' => 'HTML to PDF — convert HTML code to PDF documents instantly. Fast and online.',
        'action_label' => 'Convert to PDF',
    ],
    'optimize' => [
        'h1' => 'Optimize PDF',
        'h2' => 'Optimize PDF for archiving — PDF/A compatible',
        'description' => 'Optimize PDF files for archiving and PDF/A compatibility',
        'meta_description' => 'Optimize PDF — optimize PDF files for archiving and PDF/A compatibility. Fast and online.',
        'action_label' => 'Optimize',
    ],
];
