<?php

return [
    'merge' => [
        'h1' => 'Połącz PDF',
        'h2' => 'Połącz PDF, Word, Excel, PowerPoint, JPG i PNG w jeden dokument',
        'description' => 'Połącz PDF, Word, Excel, PowerPoint i obrazy w jeden plik PDF',
        'meta_description' => 'Połącz PDF — łącz pliki PDF, Word, Excel, PowerPoint i obrazy w jeden dokument online. Szybko, bezpiecznie i bez instalacji.',
        'action_label' => 'Połącz pliki',
    ],
    'compress' => [
        'h1' => 'Kompresuj PDF',
        'h2' => 'Zmniejsz rozmiar pliku PDF online — bez utraty jakości',
        'description' => 'Zmniejsz rozmiar pliku PDF online bez utraty jakości',
        'meta_description' => 'Kompresuj PDF — zmniejsz rozmiar dokumentów PDF online. Szybko i bez utraty jakości.',
        'action_label' => 'Kompresuj',
    ],
    'image-to-pdf' => [
        'h1' => 'Obraz do PDF',
        'h2' => 'Konwertuj dowolny obraz na PDF natychmiast — JPG, PNG, GIF, BMP, WebP i inne',
        'description' => 'Konwertuj dowolny format obrazu na PDF — JPG, PNG, GIF, BMP, WebP, TIFF, SVG',
        'meta_description' => 'Obraz do PDF — konwertuj dowolny obraz (JPG, PNG, GIF, BMP, WebP, TIFF, SVG) na dokument PDF natychmiast. Szybko, bezpiecznie i online.',
        'action_label' => 'Konwertuj na PDF',
    ],
    'jpg-to-pdf' => [
        'h1' => 'JPG do PDF',
        'h2' => 'Konwertuj obrazy na PDF natychmiast — JPG, PNG i inne',
        'description' => 'Natychmiastowa konwersja obrazów na dokumenty PDF',
        'meta_description' => 'JPG do PDF — konwertuj obrazy na dokumenty PDF natychmiast. Obsługuje JPG, PNG i inne formaty.',
        'action_label' => 'Utwórz PDF',
    ],
    'pdf-to-word' => [
        'h1' => 'PDF do Word',
        'h2' => 'Konwertuj PDF na dokument Word — edytowalny i z zachowanym formatowaniem',
        'description' => 'Konwertuj PDF na edytowalne dokumenty Word',
        'meta_description' => 'PDF do Word — konwertuj pliki PDF na edytowalne dokumenty Word. Formatowanie zachowane.',
        'action_label' => 'Konwertuj na Word',
    ],
    'word-to-pdf' => [
        'h1' => 'Word do PDF',
        'h2' => 'Zapisz dokumenty Word jako PDF natychmiast',
        'description' => 'Natychmiastowa konwersja dokumentów Word na PDF',
        'meta_description' => 'Word do PDF — konwertuj dokumenty Word na pliki PDF natychmiast. Szybko i łatwo online.',
        'action_label' => 'Konwertuj na PDF',
    ],
    'pdf-to-jpg' => [
        'h1' => 'PDF do JPG',
        'h2' => 'Eksportuj strony PDF jako obrazy — wysoka jakość',
        'description' => 'Eksportuj strony PDF jako wysokiej jakości obrazy JPG',
        'meta_description' => 'PDF do JPG — eksportuj strony PDF jako wysokiej jakości obrazy JPG. Szybko i online.',
        'action_label' => 'Konwertuj na JPG',
    ],
    'split' => [
        'h1' => 'Podziel PDF',
        'h2' => 'Podziel PDF — wyodrębnij i rozdziel strony',
        'description' => 'Podziel pliki PDF i wyodrębnij poszczególne strony',
        'meta_description' => 'Podziel PDF — podziel pliki PDF i wyodrębnij poszczególne strony. Szybko i online.',
        'action_label' => 'Podziel PDF',
    ],
    'edit' => [
        'h1' => 'Edytuj PDF',
        'h2' => 'Edytuj pliki PDF online — zmieniaj tekst i strony',
        'description' => 'Edytuj pliki PDF bezpośrednio online',
        'meta_description' => 'Edytuj PDF — edytuj pliki PDF bezpośrednio online. Zmieniaj tekst, układaj strony i więcej.',
        'action_label' => 'Edytuj PDF',
    ],
    'sign' => [
        'h1' => 'Podpisz PDF',
        'h2' => 'Dodaj podpis cyfrowy do PDF — bezpiecznie i łatwo',
        'description' => 'Dodaj swój podpis cyfrowy do dokumentów PDF',
        'meta_description' => 'Podpisz PDF — dodaj swój podpis cyfrowy bezpiecznie do dokumentów PDF. Online i bez oprogramowania.',
        'action_label' => 'Podpisz',
    ],
    'pdf-to-excel' => [
        'h1' => 'PDF do Excel',
        'h2' => 'Konwertuj tabele PDF na edytowalne pliki Excel',
        'description' => 'Konwertuj tabele PDF na arkusze Excel',
        'meta_description' => 'PDF do Excel — konwertuj tabele PDF na edytowalne pliki Excel. Szybko i online.',
        'action_label' => 'Konwertuj na Excel',
    ],
    'excel-to-pdf' => [
        'h1' => 'Excel do PDF',
        'h2' => 'Zapisz pliki Excel jako PDF natychmiast',
        'description' => 'Konwertuj pliki Excel na dokumenty PDF',
        'meta_description' => 'Excel do PDF — konwertuj pliki Excel na dokumenty PDF natychmiast. Szybko i online.',
        'action_label' => 'Konwertuj na PDF',
    ],
    'rotate' => [
        'h1' => 'Obróć PDF',
        'h2' => 'Obracaj strony PDF — 90°, 180° lub 270°',
        'description' => 'Obracaj strony PDF o 90°, 180° lub 270°',
        'meta_description' => 'Obróć PDF — obracaj strony PDF o 90°, 180° lub 270°. Szybko i online.',
        'action_label' => 'Obróć',
    ],
    'protect' => [
        'h1' => 'Zabezpiecz PDF hasłem',
        'h2' => 'Zabezpiecz PDF hasłem — bezpieczne szyfrowanie',
        'description' => 'Chroń pliki PDF hasłem',
        'meta_description' => 'Zabezpiecz PDF hasłem — zabezpiecz swoje pliki PDF hasłem. Szybko i online.',
        'action_label' => 'Zabezpiecz',
    ],
    'unlock' => [
        'h1' => 'Odblokuj PDF',
        'h2' => 'Usuń ochronę hasłem z PDF',
        'description' => 'Usuń ochronę hasłem z plików PDF',
        'meta_description' => 'Odblokuj PDF — usuń ochronę hasłem z plików PDF. Szybko i online.',
        'action_label' => 'Odblokuj',
    ],
    'watermark' => [
        'h1' => 'Dodaj znak wodny',
        'h2' => 'Dodaj tekstowy znak wodny do plików PDF',
        'description' => 'Dodaj tekstowy znak wodny do dokumentów PDF',
        'meta_description' => 'Dodaj znak wodny — dodaj tekstowy znak wodny do swoich plików PDF. Szybko i online.',
        'action_label' => 'Dodaj znak wodny',
    ],
    'page-numbers' => [
        'h1' => 'Dodaj numery stron',
        'h2' => 'Dodaj numery stron do dokumentów PDF',
        'description' => 'Dodaj numery stron do plików PDF',
        'meta_description' => 'Dodaj numery stron — dodaj numery stron do swoich dokumentów PDF. Szybko i online.',
        'action_label' => 'Dodaj numery stron',
    ],
    'pdf-to-ppt' => [
        'h1' => 'PDF do PowerPoint',
        'h2' => 'Konwertuj PDF na prezentację PowerPoint — edytowalna',
        'description' => 'Konwertuj pliki PDF na edytowalne prezentacje PowerPoint',
        'meta_description' => 'PDF do PowerPoint — konwertuj pliki PDF na edytowalne prezentacje PowerPoint. Szybko i online.',
        'action_label' => 'Konwertuj na PowerPoint',
    ],
    'ppt-to-pdf' => [
        'h1' => 'PowerPoint do PDF',
        'h2' => 'Zapisz prezentacje PowerPoint jako PDF natychmiast',
        'description' => 'Konwertuj prezentacje PowerPoint na PDF',
        'meta_description' => 'PowerPoint do PDF — konwertuj prezentacje PowerPoint na pliki PDF natychmiast. Szybko i online.',
        'action_label' => 'Konwertuj na PDF',
    ],
    'pdf-to-png' => [
        'h1' => 'PDF do PNG',
        'h2' => 'Eksportuj strony PDF jako obrazy PNG — wysoka jakość',
        'description' => 'Eksportuj strony PDF jako wysokiej jakości obrazy PNG',
        'meta_description' => 'PDF do PNG — eksportuj strony PDF jako wysokiej jakości obrazy PNG. Szybko i online.',
        'action_label' => 'Konwertuj na PNG',
    ],
    'png-to-pdf' => [
        'h1' => 'PNG do PDF',
        'h2' => 'Konwertuj obrazy PNG na PDF natychmiast',
        'description' => 'Konwertuj obrazy PNG na dokumenty PDF',
        'meta_description' => 'PNG do PDF — konwertuj obrazy PNG na dokumenty PDF natychmiast. Szybko i online.',
        'action_label' => 'Utwórz PDF',
    ],
    'ocr' => [
        'h1' => 'OCR — rozpoznaj tekst',
        'h2' => 'Wyodrębnij tekst ze zeskanowanych PDF i obrazów — OCR',
        'description' => 'Wyodrębnij tekst ze zeskanowanych PDF i obrazów (JPG, PNG, TIFF, BMP, WebP, GIF)',
        'meta_description' => 'OCR — wyodrębnij tekst ze zeskanowanych dokumentów PDF i obrazów (JPG, PNG, TIFF, BMP, WebP, GIF). Wynikiem jest przeszukiwalny PDF. Szybko i online.',
        'action_label' => 'Rozpoznaj tekst',
    ],
    'remove-pages' => [
        'h1' => 'Usuń strony',
        'h2' => 'Usuń poszczególne strony z dokumentów PDF',
        'description' => 'Usuń określone strony z plików PDF',
        'meta_description' => 'Usuń strony — usuń poszczególne strony z dokumentów PDF. Szybko i online.',
        'action_label' => 'Usuń strony',
    ],
    'extract-pages' => [
        'h1' => 'Wyodrębnij strony',
        'h2' => 'Wyodrębnij określone strony z dokumentów PDF',
        'description' => 'Wyodrębnij określone strony z plików PDF',
        'meta_description' => 'Wyodrębnij strony — wyodrębnij określone strony z dokumentów PDF. Szybko i online.',
        'action_label' => 'Wyodrębnij strony',
    ],
    'html-to-pdf' => [
        'h1' => 'HTML do PDF',
        'h2' => 'Konwertuj kod HTML na dokumenty PDF natychmiast',
        'description' => 'Konwertuj kod HTML na dokumenty PDF',
        'meta_description' => 'HTML do PDF — konwertuj kod HTML na dokumenty PDF natychmiast. Szybko i online.',
        'action_label' => 'Konwertuj na PDF',
    ],
    'optimize' => [
        'h1' => 'Optymalizuj PDF',
        'h2' => 'Optymalizuj PDF do archiwizacji — zgodny z PDF/A',
        'description' => 'Optymalizuj pliki PDF do archiwizacji i zgodności z PDF/A',
        'meta_description' => 'Optymalizuj PDF — optymalizuj pliki PDF do archiwizacji i zgodności z PDF/A. Szybko i online.',
        'action_label' => 'Optymalizuj',
    ],
];
