<?php

return [
    'merge' => [
        'h1' => 'PDF egyesítése',
        'h2' => 'PDF, Word, Excel, PowerPoint, JPG és PNG egyesítése egy dokumentumba',
        'description' => 'PDF, Word, Excel, PowerPoint és képek egyesítése egy PDF-be',
        'meta_description' => 'PDF egyesítése — PDF, Word, Excel, PowerPoint és képek egyesítése egy dokumentumba azonnal online. Gyors, biztonságos és telepítés nélküli.',
        'action_label' => 'Fájlok egyesítése',
    ],
    'compress' => [
        'h1' => 'PDF tömörítése',
        'h2' => 'Csökkentse a PDF fájlméretet online — minőségvesztés nélkül',
        'description' => 'Csökkentse a PDF fájlméretét online minőségvesztés nélkül',
        'meta_description' => 'PDF tömörítése — csökkentse a PDF dokumentumok fájlméretét online. Gyors és minőségvesztés nélkül.',
        'action_label' => 'Tömörítés',
    ],
    'image-to-pdf' => [
        'h1' => 'Kép PDF-be',
        'h2' => 'Bármilyen kép azonnali PDF-be konvertálása — JPG, PNG, GIF, BMP, WebP és több',
        'description' => 'Bármilyen képformátum konvertálása PDF-be — JPG, PNG, GIF, BMP, WebP, TIFF, SVG',
        'meta_description' => 'Kép PDF-be — bármilyen kép (JPG, PNG, GIF, BMP, WebP, TIFF, SVG) azonnali konvertálása PDF dokumentumba. Gyors, biztonságos és online.',
        'action_label' => 'Konvertálás PDF-be',
    ],
    'jpg-to-pdf' => [
        'h1' => 'JPG PDF-be',
        'h2' => 'Képek azonnali PDF-be konvertálása — JPG, PNG és több',
        'description' => 'Képek azonnali konvertálása PDF dokumentumokba',
        'meta_description' => 'JPG PDF-be — képek azonnali konvertálása PDF dokumentumokba. JPG, PNG és több formátumot támogat.',
        'action_label' => 'PDF létrehozása',
    ],
    'pdf-to-word' => [
        'h1' => 'PDF Word-be',
        'h2' => 'PDF konvertálása Word dokumentummá — szerkeszthető és formázott',
        'description' => 'PDF konvertálása szerkeszthető Word dokumentumokká',
        'meta_description' => 'PDF Word-be — PDF fájlok konvertálása szerkeszthető Word dokumentumokká. Formázás megőrizve.',
        'action_label' => 'Konvertálás Word-be',
    ],
    'word-to-pdf' => [
        'h1' => 'Word PDF-be',
        'h2' => 'Word dokumentumok mentése PDF-ként azonnal',
        'description' => 'Word dokumentumok azonnali konvertálása PDF-be',
        'meta_description' => 'Word PDF-be — Word dokumentumok azonnali konvertálása PDF fájlokká. Gyorsan és egyszerűen online.',
        'action_label' => 'Konvertálás PDF-be',
    ],
    'pdf-to-jpg' => [
        'h1' => 'PDF JPG-be',
        'h2' => 'PDF oldalak exportálása képként — kiváló minőség',
        'description' => 'PDF oldalak exportálása kiváló minőségű JPG képként',
        'meta_description' => 'PDF JPG-be — PDF oldalak exportálása kiváló minőségű JPG képként. Gyors és online.',
        'action_label' => 'Konvertálás JPG-be',
    ],
    'split' => [
        'h1' => 'PDF szétválasztása',
        'h2' => 'PDF szétválasztása — oldalak kinyerése és elválasztása',
        'description' => 'PDF fájlok szétválasztása és egyes oldalak kinyerése',
        'meta_description' => 'PDF szétválasztása — PDF fájlok szétválasztása és egyes oldalak kinyerése. Gyors és online.',
        'action_label' => 'PDF szétválasztása',
    ],
    'edit' => [
        'h1' => 'PDF szerkesztése',
        'h2' => 'PDF fájlok szerkesztése online — szöveg és oldalak módosítása',
        'description' => 'PDF fájlok közvetlen szerkesztése online',
        'meta_description' => 'PDF szerkesztése — PDF fájlok közvetlen szerkesztése online. Szöveg módosítása, oldalak átrendezése és sok más.',
        'action_label' => 'PDF szerkesztése',
    ],
    'sign' => [
        'h1' => 'PDF aláírása',
        'h2' => 'Digitális aláírás hozzáadása PDF-hez — biztonságos és egyszerű',
        'description' => 'Digitális aláírás hozzáadása PDF dokumentumokhoz',
        'meta_description' => 'PDF aláírása — adja hozzá biztonságosan a digitális aláírását PDF dokumentumokhoz. Online és szoftver nélkül.',
        'action_label' => 'Aláírás',
    ],
    'pdf-to-excel' => [
        'h1' => 'PDF Excelbe',
        'h2' => 'PDF táblázatok konvertálása szerkeszthető Excel fájlokká',
        'description' => 'PDF táblázatok konvertálása Excel táblákká',
        'meta_description' => 'PDF Excelbe — PDF táblázatok konvertálása szerkeszthető Excel fájlokká. Gyors és online.',
        'action_label' => 'Konvertálás Excelbe',
    ],
    'excel-to-pdf' => [
        'h1' => 'Excel PDF-be',
        'h2' => 'Excel fájlok mentése PDF-ként azonnal',
        'description' => 'Excel fájlok konvertálása PDF dokumentumokká',
        'meta_description' => 'Excel PDF-be — Excel fájlok azonnali konvertálása PDF dokumentumokká. Gyors és online.',
        'action_label' => 'Konvertálás PDF-be',
    ],
    'rotate' => [
        'h1' => 'PDF forgatása',
        'h2' => 'PDF oldalak forgatása — 90°, 180° vagy 270°',
        'description' => 'PDF oldalak forgatása 90°, 180° vagy 270°-kal',
        'meta_description' => 'PDF forgatása — PDF oldalak forgatása 90°, 180° vagy 270°-kal. Gyors és online.',
        'action_label' => 'Forgatás',
    ],
    'protect' => [
        'h1' => 'PDF jelszóval védése',
        'h2' => 'PDF jelszavas védelme — biztonságos titkosítás',
        'description' => 'PDF fájlok védése jelszóval',
        'meta_description' => 'PDF jelszóval védése — biztosítsa PDF fájljait jelszavas védelemmel. Gyors és online.',
        'action_label' => 'Védés',
    ],
    'unlock' => [
        'h1' => 'PDF feloldása',
        'h2' => 'Jelszavas védelem eltávolítása PDF-ről',
        'description' => 'Jelszavas védelem eltávolítása PDF fájlokról',
        'meta_description' => 'PDF feloldása — jelszavas védelem eltávolítása PDF fájlokról. Gyors és online.',
        'action_label' => 'Feloldás',
    ],
    'watermark' => [
        'h1' => 'Vízjel hozzáadása',
        'h2' => 'Szöveges vízjel hozzáadása PDF fájlokhoz',
        'description' => 'Szöveges vízjel hozzáadása PDF dokumentumokhoz',
        'meta_description' => 'Vízjel hozzáadása — szöveges vízjel hozzáadása PDF fájlokhoz. Gyors és online.',
        'action_label' => 'Vízjel hozzáadása',
    ],
    'page-numbers' => [
        'h1' => 'Oldalszámok hozzáadása',
        'h2' => 'Oldalszámok hozzáadása PDF dokumentumokhoz',
        'description' => 'Oldalszámok hozzáadása PDF fájlokhoz',
        'meta_description' => 'Oldalszámok hozzáadása — oldalszámok hozzáadása PDF dokumentumokhoz. Gyors és online.',
        'action_label' => 'Oldalszámok hozzáadása',
    ],
    'pdf-to-ppt' => [
        'h1' => 'PDF PowerPointba',
        'h2' => 'PDF konvertálása PowerPoint-prezentációba — szerkeszthető',
        'description' => 'PDF fájlok konvertálása szerkeszthető PowerPoint-prezentációkká',
        'meta_description' => 'PDF PowerPointba — PDF fájlok konvertálása szerkeszthető PowerPoint-prezentációkká. Gyors és online.',
        'action_label' => 'Konvertálás PowerPointba',
    ],
    'ppt-to-pdf' => [
        'h1' => 'PowerPoint PDF-be',
        'h2' => 'PowerPoint-prezentációk mentése PDF-ként azonnal',
        'description' => 'PowerPoint-prezentációk konvertálása PDF-be',
        'meta_description' => 'PowerPoint PDF-be — PowerPoint-prezentációk azonnali konvertálása PDF fájlokká. Gyors és online.',
        'action_label' => 'Konvertálás PDF-be',
    ],
    'pdf-to-png' => [
        'h1' => 'PDF PNG-be',
        'h2' => 'PDF oldalak exportálása PNG képként — kiváló minőség',
        'description' => 'PDF oldalak exportálása kiváló minőségű PNG képként',
        'meta_description' => 'PDF PNG-be — PDF oldalak exportálása kiváló minőségű PNG képként. Gyors és online.',
        'action_label' => 'Konvertálás PNG-be',
    ],
    'png-to-pdf' => [
        'h1' => 'PNG PDF-be',
        'h2' => 'PNG képek azonnali konvertálása PDF-be',
        'description' => 'PNG képek konvertálása PDF dokumentumokká',
        'meta_description' => 'PNG PDF-be — PNG képek azonnali konvertálása PDF dokumentumokká. Gyors és online.',
        'action_label' => 'PDF létrehozása',
    ],
    'ocr' => [
        'h1' => 'OCR — szövegfelismerés',
        'h2' => 'Szöveg kinyerése szkennelt PDF-ekből és képekből — OCR',
        'description' => 'Szöveg kinyerése szkennelt PDF-ekből és képekből (JPG, PNG, TIFF, BMP, WebP, GIF)',
        'meta_description' => 'OCR — szöveg kinyerése szkennelt PDF dokumentumokból és képekből (JPG, PNG, TIFF, BMP, WebP, GIF). A kimenet egy kereshető PDF. Gyors és online.',
        'action_label' => 'Szövegfelismerés',
    ],
    'remove-pages' => [
        'h1' => 'Oldalak eltávolítása',
        'h2' => 'Egyes oldalak eltávolítása PDF dokumentumokból',
        'description' => 'Adott oldalak eltávolítása PDF fájlokból',
        'meta_description' => 'Oldalak eltávolítása — egyes oldalak eltávolítása PDF dokumentumokból. Gyors és online.',
        'action_label' => 'Oldalak eltávolítása',
    ],
    'extract-pages' => [
        'h1' => 'Oldalak kinyerése',
        'h2' => 'Adott oldalak kinyerése PDF dokumentumokból',
        'description' => 'Adott oldalak kinyerése PDF fájlokból',
        'meta_description' => 'Oldalak kinyerése — adott oldalak kinyerése PDF dokumentumokból. Gyors és online.',
        'action_label' => 'Oldalak kinyerése',
    ],
    'html-to-pdf' => [
        'h1' => 'HTML PDF-be',
        'h2' => 'HTML kód azonnali konvertálása PDF dokumentumokba',
        'description' => 'HTML kód konvertálása PDF dokumentumokba',
        'meta_description' => 'HTML PDF-be — HTML kód azonnali konvertálása PDF dokumentumokba. Gyors és online.',
        'action_label' => 'Konvertálás PDF-be',
    ],
    'optimize' => [
        'h1' => 'PDF optimalizálása',
        'h2' => 'PDF optimalizálása archiváláshoz — PDF/A kompatibilis',
        'description' => 'PDF fájlok optimalizálása archiváláshoz és PDF/A kompatibilitáshoz',
        'meta_description' => 'PDF optimalizálása — PDF fájlok optimalizálása archiváláshoz és PDF/A kompatibilitáshoz. Gyors és online.',
        'action_label' => 'Optimalizálás',
    ],
];
