<?php

return [
    'merge' => [
        'h1' => 'Sloučit PDF',
        'h2' => 'Sloučte PDF, Word, Excel, PowerPoint, JPG a PNG do jednoho dokumentu',
        'description' => 'Sloučení PDF, Word, Excel, PowerPoint a obrázků do jednoho PDF',
        'meta_description' => 'Sloučit PDF — sloučte PDF, Word, Excel, PowerPoint a obrázky do jednoho dokumentu okamžitě online. Rychle, bezpečně a bez nutnosti instalace.',
        'action_label' => 'Sloučit soubory',
    ],
    'compress' => [
        'h1' => 'Komprimovat PDF',
        'h2' => 'Snižte velikost PDF souboru online — bez ztráty kvality',
        'description' => 'Snížit velikost PDF souboru online bez ztráty kvality',
        'meta_description' => 'Komprimovat PDF — snižte velikost svých PDF dokumentů online. Rychle a bez ztráty kvality.',
        'action_label' => 'Komprimovat',
    ],
    'image-to-pdf' => [
        'h1' => 'Obrázek do PDF',
        'h2' => 'Konvertujte jakýkoli obrázek do PDF okamžitě — JPG, PNG, GIF, BMP, WebP a další',
        'description' => 'Konvertovat jakýkoli formát obrázku do PDF — JPG, PNG, GIF, BMP, WebP, TIFF, SVG',
        'meta_description' => 'Obrázek do PDF — konvertujte jakýkoli obrázek (JPG, PNG, GIF, BMP, WebP, TIFF, SVG) do PDF dokumentu okamžitě. Rychle, bezpečně a online.',
        'action_label' => 'Konvertovat do PDF',
    ],
    'jpg-to-pdf' => [
        'h1' => 'JPG do PDF',
        'h2' => 'Konvertujte obrázky do PDF okamžitě — JPG, PNG a další',
        'description' => 'Okamžitě konvertovat obrázky do PDF dokumentů',
        'meta_description' => 'JPG do PDF — konvertujte obrázky do PDF dokumentů okamžitě. Podporuje JPG, PNG a další formáty.',
        'action_label' => 'Vytvořit PDF',
    ],
    'pdf-to-word' => [
        'h1' => 'PDF do Wordu',
        'h2' => 'Konvertujte PDF do dokumentu Word — editovatelné a formátované',
        'description' => 'Konvertovat PDF do editovatelných dokumentů Word',
        'meta_description' => 'PDF do Wordu — konvertujte PDF soubory do editovatelných dokumentů Word. Formátování zachováno.',
        'action_label' => 'Konvertovat do Wordu',
    ],
    'word-to-pdf' => [
        'h1' => 'Word do PDF',
        'h2' => 'Uložte dokumenty Word jako PDF okamžitě',
        'description' => 'Okamžitě konvertovat dokumenty Word do PDF',
        'meta_description' => 'Word do PDF — konvertujte dokumenty Word do PDF souborů okamžitě. Rychle a snadno online.',
        'action_label' => 'Konvertovat do PDF',
    ],
    'pdf-to-jpg' => [
        'h1' => 'PDF do JPG',
        'h2' => 'Exportujte stránky PDF jako obrázky — vysoká kvalita',
        'description' => 'Exportovat stránky PDF jako vysoce kvalitní JPG obrázky',
        'meta_description' => 'PDF do JPG — exportujte stránky PDF jako vysoce kvalitní JPG obrázky. Rychle a online.',
        'action_label' => 'Konvertovat do JPG',
    ],
    'split' => [
        'h1' => 'Rozdělit PDF',
        'h2' => 'Rozdělit PDF — extrahování a oddělení stránek',
        'description' => 'Rozdělit PDF soubory a extrahovat jednotlivé stránky',
        'meta_description' => 'Rozdělit PDF — rozdělte PDF soubory a extrahujte jednotlivé stránky. Rychle a online.',
        'action_label' => 'Rozdělit PDF',
    ],
    'edit' => [
        'h1' => 'Upravit PDF',
        'h2' => 'Upravujte PDF soubory online — měňte text a stránky',
        'description' => 'Upravit PDF soubory přímo online',
        'meta_description' => 'Upravit PDF — upravujte PDF soubory přímo online. Měňte text, přeskupujte stránky a další.',
        'action_label' => 'Upravit PDF',
    ],
    'sign' => [
        'h1' => 'Podepsat PDF',
        'h2' => 'Přidejte digitální podpis k PDF — bezpečně a snadno',
        'description' => 'Přidat svůj digitální podpis k PDF dokumentům',
        'meta_description' => 'Podepsat PDF — přidejte svůj digitální podpis bezpečně k PDF dokumentům. Online a bez softwaru.',
        'action_label' => 'Podepsat',
    ],
    'pdf-to-excel' => [
        'h1' => 'PDF do Excelu',
        'h2' => 'Konvertujte tabulky PDF do editovatelných souborů Excel',
        'description' => 'Konvertovat tabulky PDF do tabulek Excel',
        'meta_description' => 'PDF do Excelu — konvertujte tabulky PDF do editovatelných souborů Excel. Rychle a online.',
        'action_label' => 'Konvertovat do Excelu',
    ],
    'excel-to-pdf' => [
        'h1' => 'Excel do PDF',
        'h2' => 'Uložte soubory Excel jako PDF okamžitě',
        'description' => 'Konvertovat soubory Excel do PDF dokumentů',
        'meta_description' => 'Excel do PDF — konvertujte soubory Excel do PDF dokumentů okamžitě. Rychle a online.',
        'action_label' => 'Konvertovat do PDF',
    ],
    'rotate' => [
        'h1' => 'Otočit PDF',
        'h2' => 'Otáčejte stránky PDF — 90°, 180° nebo 270°',
        'description' => 'Otočit stránky PDF o 90°, 180° nebo 270°',
        'meta_description' => 'Otočit PDF — otáčejte stránky PDF o 90°, 180° nebo 270°. Rychle a online.',
        'action_label' => 'Otočit',
    ],
    'protect' => [
        'h1' => 'Chránit PDF heslem',
        'h2' => 'Chraňte PDF heslem — bezpečné šifrování',
        'description' => 'Chránit PDF soubory heslem',
        'meta_description' => 'Chránit PDF heslem — zabezpečte své PDF soubory heslem. Rychle a online.',
        'action_label' => 'Chránit',
    ],
    'unlock' => [
        'h1' => 'Odemknout PDF',
        'h2' => 'Odstraňte ochranu heslem z PDF',
        'description' => 'Odstranit ochranu heslem z PDF souborů',
        'meta_description' => 'Odemknout PDF — odstraňte ochranu heslem z PDF souborů. Rychle a online.',
        'action_label' => 'Odemknout',
    ],
    'watermark' => [
        'h1' => 'Přidat vodoznak',
        'h2' => 'Přidejte textový vodoznak k PDF souborům',
        'description' => 'Přidat textový vodoznak k PDF dokumentům',
        'meta_description' => 'Přidat vodoznak — přidejte textový vodoznak ke svým PDF souborům. Rychle a online.',
        'action_label' => 'Přidat vodoznak',
    ],
    'page-numbers' => [
        'h1' => 'Přidat čísla stránek',
        'h2' => 'Přidejte čísla stránek k PDF dokumentům',
        'description' => 'Přidat čísla stránek k PDF souborům',
        'meta_description' => 'Přidat čísla stránek — přidejte čísla stránek ke svým PDF dokumentům. Rychle a online.',
        'action_label' => 'Přidat čísla stránek',
    ],
    'pdf-to-ppt' => [
        'h1' => 'PDF do PowerPointu',
        'h2' => 'Konvertujte PDF do prezentace PowerPoint — editovatelné',
        'description' => 'Konvertovat PDF soubory do editovatelných prezentací PowerPoint',
        'meta_description' => 'PDF do PowerPointu — konvertujte PDF soubory do editovatelných prezentací PowerPoint. Rychle a online.',
        'action_label' => 'Konvertovat do PowerPointu',
    ],
    'ppt-to-pdf' => [
        'h1' => 'PowerPoint do PDF',
        'h2' => 'Uložte prezentace PowerPoint jako PDF okamžitě',
        'description' => 'Konvertovat prezentace PowerPoint do PDF',
        'meta_description' => 'PowerPoint do PDF — konvertujte prezentace PowerPoint do PDF souborů okamžitě. Rychle a online.',
        'action_label' => 'Konvertovat do PDF',
    ],
    'pdf-to-png' => [
        'h1' => 'PDF do PNG',
        'h2' => 'Exportujte stránky PDF jako PNG obrázky — vysoká kvalita',
        'description' => 'Exportovat stránky PDF jako vysoce kvalitní PNG obrázky',
        'meta_description' => 'PDF do PNG — exportujte stránky PDF jako vysoce kvalitní PNG obrázky. Rychle a online.',
        'action_label' => 'Konvertovat do PNG',
    ],
    'png-to-pdf' => [
        'h1' => 'PNG do PDF',
        'h2' => 'Konvertujte PNG obrázky do PDF okamžitě',
        'description' => 'Konvertovat PNG obrázky do PDF dokumentů',
        'meta_description' => 'PNG do PDF — konvertujte PNG obrázky do PDF dokumentů okamžitě. Rychle a online.',
        'action_label' => 'Vytvořit PDF',
    ],
    'ocr' => [
        'h1' => 'OCR — rozpoznat text',
        'h2' => 'Extrahujte text ze skenovaných PDF a obrázků — OCR',
        'description' => 'Extrahovat text ze skenovaných PDF a obrázků (JPG, PNG, TIFF, BMP, WebP, GIF)',
        'meta_description' => 'OCR — extrahujte text ze skenovaných PDF dokumentů a obrázků (JPG, PNG, TIFF, BMP, WebP, GIF). Výstupem je vyhledávatelný PDF. Rychle a online.',
        'action_label' => 'Rozpoznat text',
    ],
    'remove-pages' => [
        'h1' => 'Odstranit stránky',
        'h2' => 'Odstraňte jednotlivé stránky z PDF dokumentů',
        'description' => 'Odstranit konkrétní stránky z PDF souborů',
        'meta_description' => 'Odstranit stránky — odstraňte jednotlivé stránky z PDF dokumentů. Rychle a online.',
        'action_label' => 'Odstranit stránky',
    ],
    'extract-pages' => [
        'h1' => 'Extrahovat stránky',
        'h2' => 'Extrahujte konkrétní stránky z PDF dokumentů',
        'description' => 'Extrahovat konkrétní stránky z PDF souborů',
        'meta_description' => 'Extrahovat stránky — extrahujte konkrétní stránky z PDF dokumentů. Rychle a online.',
        'action_label' => 'Extrahovat stránky',
    ],
    'html-to-pdf' => [
        'h1' => 'HTML do PDF',
        'h2' => 'Konvertujte HTML kód do PDF dokumentů okamžitě',
        'description' => 'Konvertovat HTML kód do PDF dokumentů',
        'meta_description' => 'HTML do PDF — konvertujte HTML kód do PDF dokumentů okamžitě. Rychle a online.',
        'action_label' => 'Konvertovat do PDF',
    ],
    'optimize' => [
        'h1' => 'Optimalizovat PDF',
        'h2' => 'Optimalizujte PDF pro archivaci — kompatibilní s PDF/A',
        'description' => 'Optimalizovat PDF soubory pro archivaci a kompatibilitu s PDF/A',
        'meta_description' => 'Optimalizovat PDF — optimalizujte PDF soubory pro archivaci a kompatibilitu s PDF/A. Rychle a online.',
        'action_label' => 'Optimalizovat',
    ],
];
